import { motion, useInView, AnimatePresence } from 'framer-motion';
import { useRef, useState } from 'react';
import { Code2, FileCode, Server, Sparkles, Copy, Check } from 'lucide-react';
import { highlightCode, tokensToHtml } from '../lib/utils';

const codeExamples = [
  {
    id: 'client',
    label: 'Client Usage',
    icon: Code2,
    filename: 'src/components/UserList.tsx',
    language: 'typescript',
    code: `import { rpc } from '@zap-js/server';
import type { User, ListUsersResponse, ApiError } from '../generated/types';

export function UserList() {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    async function fetchUsers() {
      const result = await rpc.call<ListUsersResponse | ApiError>('list_users', {
        limit: 10,
        offset: 0
      });

      // Type-safe error handling with discriminated unions
      if ('error' in result) {
        console.error(result.code, result.error);
        return;
      }

      // TypeScript knows this is ListUsersResponse
      setUsers(result.users);
      console.log(\`Total: \${result.total}\`);
    }
    fetchUsers();
  }, []);

  return <ul>{users.map(u => <li key={u.id}>{u.name}</li>)}</ul>;
}`,
  },
  {
    id: 'rust',
    label: 'Rust Backend',
    icon: Server,
    filename: 'server/src/main.rs',
    language: 'rust',
    code: `use zap::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub id: String,
    pub name: String,
    pub email: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiError {
    pub error: String,
    pub code: String,
}

/// List all users with pagination
#[export]
pub fn list_users(limit: u32, offset: u32) -> Result<ListUsersResponse, ApiError> {
    let users = get_mock_users();
    Ok(ListUsersResponse {
        users,
        total: 100,
        limit: limit as usize,
        offset: offset as usize,
        has_more: offset + limit < 100,
    })
}`,
  },
  {
    id: 'generated',
    label: 'Auto-Generated',
    icon: Sparkles,
    filename: 'src/generated/types.ts',
    language: 'typescript',
    code: `// Auto-generated TypeScript types from Rust
// DO NOT EDIT - Generated by zap-codegen

export interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  createdAt: string;
}

export interface ListUsersResponse {
  users: User[];
  total: number;
  limit: number;
  offset: number;
  hasMore: boolean;
}

export interface ApiError {
  error: string;
  code: string;
}

// Use with @zap-js/client:
// import { rpc } from '@zap-js/server';
// const result = await rpc.call<User | ApiError>('get_user', { id: '123' });`,
  },
  {
    id: 'usage',
    label: 'Full Example',
    icon: FileCode,
    filename: 'src/components/Dashboard.tsx',
    language: 'typescript',
    code: `import { useState, useEffect } from 'react';
import { rpc } from '@zap-js/server';
import type { StatsResponse, ApiError } from '../generated/types';

export function Dashboard() {
  const [stats, setStats] = useState<StatsResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadStats() {
      const result = await rpc.call<StatsResponse | ApiError>('get_stats', {});

      if ('error' in result) {
        setError(result.error);
      } else {
        setStats(result);
      }
      setLoading(false);
    }
    loadStats();
  }, []);

  if (loading) return <p>Loading...</p>;
  if (error) return <p className="text-red-500">Error: {error}</p>;

  return (
    <div>
      <h1>Dashboard</h1>
      <p>Version: {stats.version}</p>
      <p>Uptime: {stats.uptime}</p>
      <p>Requests: {stats.requests.toLocaleString()}</p>
    </div>
  );
}`,
  },
];

function CodeBlock({ code, language }: { code: string; language: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const lang = language === 'rust' ? 'rust' : 'typescript';
  const highlighted = tokensToHtml(highlightCode(code, lang));

  return (
    <div className="relative group">
      <button
        onClick={handleCopy}
        className="absolute top-3 right-3 p-2 bg-carbon-800 hover:bg-carbon-700 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity z-10"
      >
        {copied ? (
          <Check className="w-4 h-4 text-emerald-400" />
        ) : (
          <Copy className="w-4 h-4 text-carbon-400" />
        )}
      </button>
      <pre className="overflow-x-auto p-4 sm:p-6 text-sm leading-relaxed">
        <code
          className="font-mono"
          dangerouslySetInnerHTML={{ __html: highlighted }}
        />
      </pre>
    </div>
  );
}

export default function CodeDemo() {
  const [activeTab, setActiveTab] = useState('client');
  const ref = useRef<HTMLDivElement>(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  const activeExample = codeExamples.find(e => e.id === activeTab)!;

  return (
    <section id="code" className="relative py-24 sm:py-32">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 mb-6 bg-emerald-500/10 border border-emerald-500/20 rounded-full">
            <Code2 className="w-4 h-4 text-emerald-400" />
            <span className="text-sm font-medium text-emerald-400">Code Examples</span>
          </div>

          <h2 className="font-display font-black text-4xl sm:text-5xl text-white mb-6">
            Rust to TypeScript,{' '}
            <span className="text-gradient">automatically</span>
          </h2>

          <p className="text-lg text-carbon-400 max-w-3xl mx-auto">
            Mark functions with #[zap::export]. Types flow to your frontend.
          </p>
        </motion.div>

        {/* Code editor mockup */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="relative"
        >
          {/* Glow effect */}
          <div className="absolute -inset-4 bg-gradient-to-r from-zap-500/20 via-violet-500/20 to-sky-500/20 rounded-3xl blur-2xl opacity-50" />

          {/* Editor window */}
          <div className="relative bg-carbon-900/80 backdrop-blur-xl border border-carbon-800 rounded-2xl overflow-hidden shadow-2xl">
            {/* Window controls */}
            <div className="flex items-center justify-between px-4 py-3 bg-carbon-900/50 border-b border-carbon-800">
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500/80" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                <div className="w-3 h-3 rounded-full bg-green-500/80" />
              </div>
              <div className="flex items-center gap-1 px-3 py-1 bg-carbon-800 rounded-lg">
                <activeExample.icon className="w-4 h-4 text-carbon-400" />
                <span className="text-sm text-carbon-400 font-mono">{activeExample.filename}</span>
              </div>
              <div className="w-20" />
            </div>

            {/* Tabs */}
            <div className="flex border-b border-carbon-800 overflow-x-auto">
              {codeExamples.map((example) => (
                <button
                  key={example.id}
                  onClick={() => setActiveTab(example.id)}
                  className={`flex items-center gap-2 px-4 sm:px-6 py-3 text-sm font-medium transition-colors whitespace-nowrap ${
                    activeTab === example.id
                      ? 'text-white bg-carbon-800/50 border-b-2 border-zap-500'
                      : 'text-carbon-500 hover:text-carbon-300 hover:bg-carbon-800/30'
                  }`}
                >
                  <example.icon className="w-4 h-4" />
                  <span className="hidden sm:inline">{example.label}</span>
                </button>
              ))}
            </div>

            {/* Code content */}
            <AnimatePresence mode="wait">
              <motion.div
                key={activeTab}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2 }}
              >
                <CodeBlock code={activeExample.code} language={activeExample.language} />
              </motion.div>
            </AnimatePresence>
          </div>
        </motion.div>

        {/* Flow explanation */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.4 }}
          className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6"
        >
          {[
            {
              step: '1',
              title: 'Write Rust',
              description: 'Add #[zap::export] to any async function.',
              color: 'rust',
            },
            {
              step: '2',
              title: 'Types Generated',
              description: 'Save the file. TypeScript bindings appear.',
              color: 'zap',
            },
            {
              step: '3',
              title: 'Call from React',
              description: 'Call server.* with full autocomplete.',
              color: 'sky',
            },
          ].map((item, i) => (
            <div
              key={item.step}
              className="relative p-6 bg-carbon-900/30 border border-carbon-800/50 rounded-xl"
            >
              <div className={`absolute -top-3 -left-3 w-8 h-8 bg-${item.color}-500/20 border border-${item.color}-500/30 rounded-lg flex items-center justify-center`}>
                <span className={`text-sm font-bold text-${item.color}-400`}>{item.step}</span>
              </div>
              <h3 className="font-semibold text-white mb-2 mt-2">{item.title}</h3>
              <p className="text-sm text-carbon-400">{item.description}</p>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
